// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: common/Pager.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pager_Sort int32

const (
	Pager_ASC  Pager_Sort = 0
	Pager_DESC Pager_Sort = 1
)

// Enum value maps for Pager_Sort.
var (
	Pager_Sort_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Pager_Sort_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Pager_Sort) Enum() *Pager_Sort {
	p := new(Pager_Sort)
	*p = x
	return p
}

func (x Pager_Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pager_Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_common_Pager_proto_enumTypes[0].Descriptor()
}

func (Pager_Sort) Type() protoreflect.EnumType {
	return &file_common_Pager_proto_enumTypes[0]
}

func (x Pager_Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pager_Sort.Descriptor instead.
func (Pager_Sort) EnumDescriptor() ([]byte, []int) {
	return file_common_Pager_proto_rawDescGZIP(), []int{0, 0}
}

type Pager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                // 页码
	Limit int32      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                              // 分页数
	Total int32      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                              // 总数，做返回值时有
	Sort  string     `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`                                 //排序字段
	Order Pager_Sort `protobuf:"varint,5,opt,name=order,proto3,enum=proto.common.Pager_Sort" json:"order,omitempty"` // 排序方式
}

func (x *Pager) Reset() {
	*x = Pager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Pager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pager) ProtoMessage() {}

func (x *Pager) ProtoReflect() protoreflect.Message {
	mi := &file_common_Pager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pager.ProtoReflect.Descriptor instead.
func (*Pager) Descriptor() ([]byte, []int) {
	return file_common_Pager_proto_rawDescGZIP(), []int{0}
}

func (x *Pager) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pager) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pager) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pager) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *Pager) GetOrder() Pager_Sort {
	if x != nil {
		return x.Order
	}
	return Pager_ASC
}

var File_common_Pager_proto protoreflect.FileDescriptor

var file_common_Pager_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x50, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x22, 0xa6, 0x01, 0x0a, 0x05, 0x50, 0x61, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x12, 0x2e, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x22, 0x19, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x43, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_Pager_proto_rawDescOnce sync.Once
	file_common_Pager_proto_rawDescData = file_common_Pager_proto_rawDesc
)

func file_common_Pager_proto_rawDescGZIP() []byte {
	file_common_Pager_proto_rawDescOnce.Do(func() {
		file_common_Pager_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_Pager_proto_rawDescData)
	})
	return file_common_Pager_proto_rawDescData
}

var file_common_Pager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_Pager_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_Pager_proto_goTypes = []interface{}{
	(Pager_Sort)(0), // 0: proto.common.Pager.Sort
	(*Pager)(nil),   // 1: proto.common.Pager
}
var file_common_Pager_proto_depIdxs = []int32{
	0, // 0: proto.common.Pager.order:type_name -> proto.common.Pager.Sort
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_Pager_proto_init() }
func file_common_Pager_proto_init() {
	if File_common_Pager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_Pager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_Pager_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_Pager_proto_goTypes,
		DependencyIndexes: file_common_Pager_proto_depIdxs,
		EnumInfos:         file_common_Pager_proto_enumTypes,
		MessageInfos:      file_common_Pager_proto_msgTypes,
	}.Build()
	File_common_Pager_proto = out.File
	file_common_Pager_proto_rawDesc = nil
	file_common_Pager_proto_goTypes = nil
	file_common_Pager_proto_depIdxs = nil
}
